### Get basic information about the server

GET http://{{$dotenv SERVERNAME}}:{{$dotenv SERVERPORT}}

### Get all students from the server

GET http://{{$dotenv SERVERNAME}}:{{$dotenv SERVERPORT}}/api/getall

### Get a student by ID

GET http://{{$dotenv SERVERNAME}}:{{$dotenv SERVERPORT}}/api/getonerow/1 

### Add a new student with POST method

POST http://{{$dotenv SERVERNAME}}:{{$dotenv SERVERPORT}}/api/insert
Content-Type: application/json

{
    "id": 321,
    "fname": "Patrick",
    "lname": "Jane",
    "birth": "1979-06-04"
}

### Update student with PUT method

PUT http://{{$dotenv SERVERNAME}}:{{$dotenv SERVERPORT}}/api/update
Content-Type: application/json

{
    "id": 321,
    "birth": "1979-06-05"
}